---
applications:
- name: open-forest-platform-frontend
  path: ../../../frontend/dist
  routes:
   - route: openforest.fs.usda.gov
  memory: 64M
  disk_quota: 6G
  instances: 2
  buildpack: https://github.com/cloudfoundry/staticfile-buildpack.git
  env:
    FORCE_HTTPS: true
  services:
    - new-relic
   