---
applications:
- name: forest-service-epermit
  path: ../../../frontend/dist
  routes:
   - route: openforest.fs.usda.gov
  memory: 64M
  buildpack: https://github.com/cloudfoundry/staticfile-buildpack.git
  env:
    FORCE_HTTPS: true
  services:
    - new-relic
