engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- "frontend/node_modules/"
- "frontend/e2e/"
- "server/node_modules/"
- "server/test/"
- "server/dba/"
- "*.spec.ts"
