language: java
jdk:
  - oraclejdk8
node_js:
  - "iojs"
  - '7'
before_script:
  - pwd
  - nvm install 7
#  - cd templates; npm install
script:
#  - npm run build
  - ./run-builds.sh
deploy:
  - provider: script
    script: "./cg-deploy/deploy.sh fs-intake-prod"
    skip_cleanup: true
    on:
      repo: 18F/fs-intake-module
      branch: master
  - provider: script
    script: "./cg-deploy/deploy.sh fs-intake-staging"
    skip_cleanup: true
    on:
      repo: flexion/fs-intake-module
#      condition: ${TRAVIS_BRANCH:0:7} = "sprint-"
      branch: "sprint-3-development"
