language: java
jdk:
  - oraclejdk8
node_js:
  - "iojs"
  - '7'
before_script:
- nvm install 7
- npm install -g yarn
- cd templates; npm install
script:
  - npm run build
before_deploy:
- cd ..
deploy:
  - provider: script
    script: "./cg-deploy/deploy.sh fs-intake-prod"
    skip_cleanup: true
    on:
      repo: 18F/fs-intake-module
      branch: master
  - provider: script
    script: "./cg-deploy/deploy.sh fs-intake-staging"
    skip_cleanup: true
    on:
      repo: flexion/fs-intake-module
      branch: master
