language: java
jdk:
    - oraclejdk8
node_js:
- '7'
before_script:
- pwd
- cd templates; npm install
script:
- node_modules/.bin/gulp copy
- node_modules/.bin/gulp pug
before_deploy:
- cd ..
- pwd
deploy:
  - provider: script
    script: "./cg-deploy/deploy.sh fs-intake-prod"
    skip_cleanup: true
    on:
      repo: 18F/fs-middlelayer-api
      branch: master
  - provider: script
    script: "./cg-deploy/deploy.sh fs-intake-staging"
    skip_cleanup: true
    on:
      repo: flexion/fs-intake-module
      branch: master
