---
applications:
- name: open-forest-platform-api-dev
  routes:
    - route: fs-intake-api-staging.app.cloud.gov
  path: ../../../server
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack
  memory: 256M
  instances: 1
  disk_quota: 2G
  services:
    - eauth-service-provider
    - intake-client-service
    - intake-db
    - intake-s3
    - login-service-provider
    - middlelayer-service
    - smtp-service
    - pay-gov
    - jwt
    - new-relic
    - feature-flags
