---
applications:
- name: open-forest-platform-frontend-staging
  path: ../../../frontend/dist
  memory: 64M
  host: open-forest-dev
  buildpack: https://github.com/cloudfoundry/staticfile-buildpack.git
  env:
    FORCE_HTTPS: true
  services:
    - new-relic
